### ISSUE TITLE
use of validation data and model extraction

### ISSUE THREAD

**Issue by TobiasMerlin** [ipazc/deepevolution#1]
Hallo Iván,

first of all, thank you for your code, it is hard to find a good one for keras.
My first question is regarding the model validation. I did not quite find a way to implement a validaition dataset method in your code. Normally you generate a test/train dataset, a validation datasat and a testset. With your code, the model is trained on the train/test dataset AND validated against it. I would like to use a validation dataset for that use. In Keras you would implement this with validation_split or a pre-defined validation dataset. Is there a way to implement this without changing the deepevolution code itself?

Second question is about extracting the best fitted model. Somehow keras does not use the best fitted model for other functions (model.summary; model.predict...) but only uses the initial model. Is there a special kind of model call needed?

**Comment by ipazc** [comment]
Hi TobiasMerlin,

the implementation does not have the validation option available and it requires to change the code. Even though, you can use the `evolve()` generator and have a manual evaluation of the model between epochs, something like:

```python
for _, best_score, mean_score, std_score in model.evolve(X, Y, max_generations, fitness_func, population, top_k, mutation_rate, mutation_std):
    validation = model.evaluate(X_val, Y_val)
```

Regarding the question of extracting the best fitted model, it is supposed that the best model is stored in the weights of the model at the end of every epoch. Maybe we can have a test example to check it out?

**Comment by TobiasMerlin** [comment]
Hi Iván,

thanks for your answer. The implementation works:) And regarding the Problem with the Model extraction, it seems that was my fault. I made a mistake withe the Model callbacks. So i will close this comment
